[package]
org = "saajid"
name = "backend_2"
version = "0.1.0"
distribution = "2201.8.6"

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.7.0"

[build-options]
observabilityIncluded = true