[package]
org = "saajid"
name = "backend"
version = "0.1.0"
distribution = "2201.8.6"
# distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.7.0"

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
path="./libs/mysql-connector-java-8.0.26.jar"