[package]
org = "saajid"
name = "backend"
distribution = "2201.8.6"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.7.0"
